src/fn/convert-contact-forms.js
test/data/generate-contact-forms/clinic-create.expected.xml
test/data/generate-contact-forms/district_hospital-create.expected.xml
test/data/generate-contact-forms/health_center-create.expected.xml

Closes #22 
@abbyad does this look like it's making the correct changes to the XML?  It may be easiest to compare at https://github.com/medic/medic-configurer/pull/25/files?w=1

Move new contact creation form to first page

---

src/fn/upload-custom-translations.js
test/fn/upload-custom-translations.spec.js

The field default was renamed to generic in webapp

Fix field renaming

---

src/cli/shell-completion-setup.js

Fix shell completion

---

package.json
src/fn/compile-app-settings.js
test/data/compile-app-settings/merge-purging-functino/app_settings.expected.json
test/data/compile-app-settings/merge-purging-functino/project/app_settings.json
test/data/compile-app-settings/purging-function/app_settings.expected.json

Purging.js document should create function "purge.fn"

---

src/nools/lib.js
test/nools/lib.tasks.spec.js

Fixing both #148 and #140 here since they are the same line of code

Ensure unique task ids given unique or default ids for events

---

src/lib/parse-targets.js
test/nools/lib.targets.spec.js

Subtitle translation key should not be required

---

src/nools/lib.js
test/nools/lib.targets.spec.js
test/nools/lib.tasks.spec.js

Function `modifyContent` parameters are undefined for tasks with `appliesTo: 'contacts'`

---

src/lib/compile-contact-summary.js

#103 for contact-summaries 
Alex's fix addressed only the nools files.

Config with mix of declarative config files and legacy config files should assert

---

README.md

https://github.com/medic/medic-conf/issues/182

Update documents referencing medic-conf after changes to argument parsing

---

package.json
src/bin/medic-conf.js

Set extraArgs to undefined when unspecified

---

release-notes.md

v2.0.x Release Notes

---

.travis.yml
package-lock.json
package.json
test/api-stub.js
test/lib/main.spec.js

Add support for Node 12

---

src/nools/lib.js
test/nools/lib.targets.spec.js

target.idType can be a function

---

package-lock.json
package.json

I published this package, but have yet to commit the change to the package.json file.

Bump package.json version to 2.2

---

src/lib/compile-nools-rules.js
src/nools/.jshintrc

Jshint should allow global user object in declarative configuration code

---

src/contact-summary/lib.js
src/fn/csv-to-docs.js
src/nools/lib.js
test/data/csv-to-docs/relationships/csv/contact.pharmacist.csv
test/data/csv-to-docs/relationships/csv/contact.pharmacy.csv
test/data/csv-to-docs/relationships/expected-json_docs/c75319ff-23cd-50cd-907b-1c8cb21320a0.doc.json
test/data/csv-to-docs/relationships/expected-json_docs/e6113424-4c27-5b7b-a611-0e947d01d83e.doc.json

Support configurable hierarchy

---

src/nools/lib.js
test/nools/lib.tasks.spec.js

Make appliesToType optional when appliesTo is contacts

---

release-notes.md

Release notes for medic-conf 3.0

---

package-lock.json
package.json
src/nools/task-emitter.js
test/nools/task-emitter.spec.js
test/run-nools-lib.js

Ability to control which contact is associated with emitted task

---

src/fn/backup-all-forms.js
src/fn/delete-all-forms.js
src/lib/db.js
src/lib/forms-list.js

Also refactors the forms list function so we no longer modify the
PouchDB object.
medic/medic#5652

Refactor to use doc_by_type so forms view can be removed

---

src/fn/fetch-csvs-from-google-drive.js
src/fn/fetch-forms-from-google-drive.js
src/lib/fetch-files-from-google-drive.js
src/lib/generate-users-csv.js

Fixes issue with fetching from google drive and executing command csv-to-docs
https://github.com/medic/medic-conf/issues/221

Fixes commands csv-to-docs and those relying on fetching from google drive

---

src/fn/initialise-project-layout.js
test/fn/initialise-project-layout.spec.js

This file is no longer used in the new declaritive task config.

Drop legacy tasks file

---

src/contact-summary/contact-summary-emitter.js
src/nools/target-emitter.js
test/data/compile-contact-summary/configurable-hierarchies/contact-summary.templated.js
test/data/compile-contact-summary/templated/contact-summary.templated.js
test/lib/compile-contact-summary.spec.js
test/nools/target-emitter.spec.js

Adds checks for contact-type in `contact-summary-emitter` and `target-emitter`
#260

Adds more checks for `contact_type`

---

src/lib/args-form-filter.js
src/lib/convert-forms.js
src/lib/upload-forms.js
test/lib/convert-forms.spec.js
test/lib/upload-forms.spec.js

ExtraArg prefixed by -- should not filter forms

---

package-lock.json
package.json
src/fn/upload-custom-translations.js
test/data/upload-custom-translations/escaped-exclamation/translations/messages-en.properties
test/fn/upload-custom-translations.spec.js

https://github.com/medic/medic-conf/issues/259

Removes double escaping

---

src/contact-summary/contact-summary-emitter.js
test/contact-summary/contact-summary-emitter.spec.js

https://github.com/medic/cht-core/issues/5856

Allows appliesToType to be an array

---

README.md

Added intro, and did a pass to move out content that was too detailed, via https://github.com/medic/medic-docs/pull/159
Still to do:

Clean up of readme

---

release-notes.md
src/lib/compile-nools-rules.js
src/lib/parse-targets.js
src/lib/validate-declarative-schema.js
src/nools/target-emitter.js
test/nools/target-emitter.spec.js
test/run-nools-lib.js

medic/cht-core#5493
Pull Requests in Three Branches:
* Muso: medic/medic-projects#7097
* Medic-Conf: #277
* WebApp: https://github.com/medic/cht-core/pull/6178
Base branch is https://github.com/medic/medic-conf/pull/275. Rebase to master and merge only after that PR merges.

5493 - Declarative Config - Support for groupBy attribute in targets

---

release-notes.md
src/lib/parse-targets.js
src/lib/validate-declarative-schema.js

https://github.com/medic/medic-conf/issues/283
Based on UAT and feedback during documentation review (medic/medic-docs#164) this PR renames passGroupWithCount to passesIfGroupCount.

Declarative Config - Rename passGroupWithCount to passesIfGroupCount

---

package-lock.json
package.json
src/lib/main.js

Replace deprecated dependency opn

---

package.json
src/lib/parse-targets.js
src/lib/validate-declarative-schema.js

https://github.com/medic/cht-core/issues/6002
https://github.com/medic/cht-core/issues/6211
Associated PR https://github.com/medic/cht-core/pull/6214

Update declarative schema to allow DHIS attributes on targets

---

package-lock.json
src/lib/parse-targets.js
test/data/compile-app-settings/targets.js/app_settings.expected.json
test/data/compile-app-settings/targets.js/project/targets.js

Propagates "visible: false" properties into compiled app settings.
medic/cht-core#6211

Allow for falsy properties in tasks. 

---

src/contact-summary/.eslintrc
src/lib/parse-targets.js
src/lib/validate-declarative-schema.js

Adds the optional "aggregate" property to target configuration. 
https://github.com/medic/cht-core/issues/4839

Adds target "aggregate" property.

---

src/cli/usage.js

Added options to synopsis

---

src/nools/task-emitter.js
test/nools/mocks.js
test/nools/task-emitter.spec.js

Handle unknown contact in task emitter

---

package.json
src/fn/csv-to-docs.js
src/fn/edit-contacts.js
src/lib/safe-stringify.js
test/lib/safe-stringify.spec.js

Replaces the custom function with a 3rd party and includes unit
tests to make sure it works as expected.
medic/medic-conf#315

Handle nulls in safe stringify fn

---

src/contact-summary/contact-summary-emitter.js
test/contact-summary/contact-summary-emitter.spec.js

Contact summary appliesIf should default to true

---

src/fn/csv-to-docs.js
test/data/csv-to-docs/relationships/csv/contact.district.csv
test/data/csv-to-docs/relationships/csv/contact.pharmacy.csv
test/data/csv-to-docs/relationships/expected-json_docs/81e956c5-932e-572b-85fe-79d65e82dbd2.doc.json
test/data/csv-to-docs/relationships/expected-json_docs/88687c94-4fe9-5870-925c-a4805f06e7ba.doc.json
test/data/csv-to-docs/relationships/expected-json_docs/c75319ff-23cd-50cd-907b-1c8cb21320a0.doc.json
test/fn/csv-to-docs.spec.js

Expand csv-to-docs to support configurable hierarchy

---

src/lib/upload-forms.js
test/data/lib/upload-forms/merge-properties/forms/example.properties.json
test/lib/upload-forms.spec.js

Allow specifying subject_key in properties

---

README.md
package-lock.json
package.json

Change releasing instructions and add beta releasing instructions

---

.npmignore
README.md
package-lock.json
package.json
release-notes.md

Also edits builds badge in readme. 

Adds release notes for 3.4.0

---

.npmignore
package-lock.json
package.json

because I messed up, and these are required to compile the app. 

Remove eslintrc files from npmignore

---

.eslintrc
.npmignore
package-lock.json
package.json
src/contact-summary/.eslintrc
src/fn/create-users.js
src/lib/api.js
src/lib/environment.js
src/lib/get-api-url.js
src/lib/warn-upload-overwrite.js
src/nools/.eslintrc
test/lib/api.spec.js

Also adds linting to stop this happening again, and unit tests for
this specific function.
#387

Fix regression to re-enable Node 8 support 

---

release-notes.md

Adds release notes for 3.5.0

---

src/nools/task-emitter.js
test/nools/task-emitter.spec.js

Pass "event" to modifyContent.

---

release-notes.md

Adds release notes for 3.6.0

---

README.md

[description]
medic/cht-conf#[number]

chore: updates medic branding

---

README.md
package.json
src/fn/move-contacts.js
test/fn/move-contacts.spec.js
test/scripts/wait_for_response_code.sh

Refactors the recursive function to not pass many parameters multiple times. 

Adds docker CouchDB to run integration tests

---

src/lib/api.js
test/lib/api.spec.js

fix(#460): log useful error messages when api connection fails

---

.github/workflows/build.yml

[description]
medic/cht-conf#[number]

add node 14 and 16

---

.eslintrc
package-lock.json
package.json
src/bin/index.js
src/cli/check-node-version.js
src/cli/shell-completion-setup.js
src/fn/check-git.js
src/fn/compress-images.js
src/fn/create-users.js
src/fn/move-contacts.js
src/fn/upload-custom-translations.js
src/fn/upload-docs.js
src/lib/api.js
src/lib/main.js
test/fn/create-users.spec.js
test/fn/move-contacts.spec.js
test/fn/upload-custom-translations.spec.js
test/fn/upload-docs.spec.js
test/lib/api.spec.js
test/lib/main.spec.js

fix(#465): remove process.exit and extraneous require

---

src/fn/move-contacts.js
test/fn/move-contacts.spec.js

move-contacts usage docs

---

src/fn/initialise-project-layout.js
test/fn/initialise-project-layout.spec.js

- medic/cht-conf #302 
-  Adds test `harness.defaults.json` file and `test` folders/sub-folders

Add "templated" extension on contact summary and test directories on initialise-project-layout

---

src/lib/lineage-constraints.js
test/fn/watch-project.spec.js

Remove sensitive words

---

test/fn/upload-custom-translations.spec.js
test/fn/watch-project.spec.js
test/lib/upload-configuration-docs.spec.js
test/lib/upload-forms.spec.js
test/lib/warn-upload-overwrite.spec.js

Fix for intermittent test failure "Server already started"

---

.github/workflows/build.yml

chore: bump ci dependencies

---

.github/workflows/build.yml
.github/workflows/release.yml
src/lib/package-lib.js

Support Node 18

---

.github/workflows/release.yml

chore: updates release action dependencies

---

src/fn/upload-extension-libs.js
src/lib/main.js
src/lib/project-paths.js
test/fn/upload-extension-libs.spec.js

feat(#547): add command for uploading extension libs

---

src/fn/compile-app-settings.js

feat(#580): publish recent commits to npm

---

test/lib/validate-app-settings.spec.js

medic/cht-conf#578
Actual work already done on #579 , adding this to release with proper commit format. 

#578 schedule start_from

---

.sonarcloud.properties

Step `#1` of [adding a new repo to Sonar Cloud](https://docs.communityhealthtoolkit.org/contribute/code/static-analysis/#adding-a-new-repo-to-sonarcloud).

chore: add .sonarcloud.properties file

---

package-lock.json
package.json
src/lib/compilation/package-lib.js
test/lib/compilation/compile-contact-summary.spec.js

medic/cht-conf#621
medic/cht-conf#539

chore(#621): update webpack to v5

---

.github/workflows/build.yml
.github/workflows/release.yml

[description]
medic/cht-conf#644

fix(#644): support node 22

---

src/fn/edit-contacts.js

Refactoring that is the result of discussions from the Dev Workshops.  No functionality should be affected by these changes.

chore: refactor edit-contacts code to reduce complexity

---

README.md

chore: bump copyright year to 2025

---

README.md

Add note in README on how to obtain the session-token for session authentication.

chore: add note on how to obtain the session-token for session authentication

---

.github/conventional-commits.yml

Created conventional commit file to add pr title linting workflow in Github CI.
Closes #685 

feat(#685): added PR title linting workflow in GitHub CI

---

src/nools/task-emitter.js
test/nools/mocks.js
test/nools/task-emitter.spec.js
test/run-nools-lib.js

Extended the priority function to include event, dueDate, and scheduledTaskIdx as arguments. This allows for more context-aware priority calculations and better task management.
Closes #692

feat(#692): update the priority function to accept additional parameters

---

test/e2e/cht-docker-utils.js

Merging https://github.com/medic/cht-core/pull/10207 broke the e2e tests here which were hard-linked to `docker-helper-4.x`.  The e2e tests failed with an odd error ([example](https://github.com/medic/cht-conf/actions/runs/17293480211/job/49137141177?pr=742)) where the tests times out with no error messages and we only try polling for a CHT instance once.
This PR updates the link to properly fetch the docker-helper script and also updates the fetch code to actually fail when a there is an error code in the response.  (Previously it was just writing "404: Not Found" to the `file` and ending the response stream successfully....)
- …

chore: update docker-helper script link to fix e2e tests
