medic/cht-conf

src/bin/medic-conf.js

For importing/exporting settings we now use an API endpoint rather
than a couchapp route so we need to use the API port. This makes the
environment variable implementation equivalent to the default --local
and remote implementations which already use the API port.
medic/medic-conf#75

Replaces the CouchDB port with default API port

---

src/fn/upload-custom-translations.js
test/fn/upload-custom-translations.spec.js

Changed the structure of translations to enable full overwrite in order to reflect addition/deletion of translation keys.
Now, the structure of the translation doc is: `{....., "custom":{...}, "default":{...}}`
* `"custom":{...}` has the custom translations uploaded via `medic-conf`
* `"default":{...}` has the default translations
Related `medic-webapp` PR: https://github.com/medic/medic-webapp/pull/4970
medic/medic-webapp#3128

Overwrite custom properties

---

src/lib/check-for-updates.js

Medic-conf was choking and could not progress if it got an error for example this one below
`ERROR SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at request.get.then.res (/Users/kennethatria/.nvm/versions/node/v8.11.0/lib/node_modules/medic-conf/src/lib/check-for-updates.js:14:20) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)`
So I created a minor fix.

Allow medic conf to progress even when it can not get the latest update data

---

scripts/changelog

- Understands when there is no new tag to work under and uses master
- Generates the release date based on the tag date
- Links to the tag in the title
- Links to each commit in each bullet point
Example: https://gist.github.com/cf710c985512dd8ab35b6ed46fb38505

Improve changelog generation

---

src/bin/medic-conf.js

This warn occurs regardless of whether you're uploading anything. You
could be backing up online configuration, or really interacting via
this tool in any way.

Modify phrasing to be more accurate

---

src/nools/lib.js
test/nools/lib.targets.spec.js

These two issues are due to inconsistencies between how targets with `appliesTo: 'reports'` and `appliesTo: 'contacts'` are processed. The code paths are very different, supporting some features for reports and some features for contacts. This converges the code paths and supports all features for both. 
#149 and #144 
While I'm in there, I'm going to get merge conflicts if I fix this one elsewhere. Changing where this `emitCustom` function is called and the data that is passed to it.
#143 
EDIT: Now also contains #158.

Converge target emit code for reports and contacts to shared function

---

.travis.yml
package-lock.json
package.json
src/bin/medic-conf.js
test/bin/medic-conf.spec.js

Args can now be passed in any order, using minimist. CLI is backwards compatible with existing conventions, and also allows for using = if people prefer.
e.g.:
--instance foo.bar
and
--instance=foo.bar
Are equivalent.
In testing I also found the changelog command was broken so I fixed that while I was in there.

More robust argument parsing using minimist

---

src/fn/backup-all-forms.js

Fixes #171
Image attachments are saved under an images sub-folder which wasn't
present at the time of writing to disk.

Ensure path exists before saving form attachment to disk

---

src/bin/medic-conf.js
src/cli/usage.js

In cases where you run docker locally or anywhere a self signed cert might be used. This flag tells node to ignore the error.

Adding a flag to allow self signed certs when using medic-conf

---

package-lock.json
package.json

This change effectively undoes https://github.com/medic/medic-conf/commit/9f945bc7f436abdab432cdd0de6cf4ef6c61f11b. Using uglify-js v3.4 has blocked up the upgrade of the `@medic/contact-summary-testing` package...  If I'm going to wage this war against uglify, I'm going to do it on latest.

Bump uglify-js to latest

---

package.json
src/bin/shell-completion.js
src/cli/usage.js
src/fn/compile-app-settings.js
src/lib/execute-action.js
src/lib/main.js
test/bin/shell-completion.spec.js
test/lib/main.spec.js

Moved the executeAction code into a module and now medic-conf can be required after npm install. Now we can use the medic-conf code to apply configs from code.

Making the execute action a module so it can be used by other scripts

---

src/lib/main.js

The csv-to-docs and upload-docs actions are used to upload test data,
and as such don't really make sense as part of the default upload.

Remove record uploading from default actions

---

README.md

Adding documentation on how to user csv-to-docs to generate a users.csv file that links to contacts and places generated while running csv-to-docs. 
@jonathanbataire  can you review this and see if it solves the issue you had opened a pull request for?

details on how to link users to contacts while running csvs

---

.auditrc.json
package.json

For some reason hashing the package-lock.json is not reliable
and we keep getting false alarms. Instead we're going to
manually run audit and check the results once every release
cycle.
medic/medic#5521

Remove npm audit check

---

src/lib/package-lib.js

As described here: https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
config/default:
./contact-summary.js  277 KiB
to
./contact-summary.js  67.8 KiB
https://github.com/medic/cht-core/issues/6115
https://github.com/medic/medic-conf/issues/224

Removes all moment locale files with webpack’s IgnorePlugin

---

src/lib/compile-nools-rules.js
src/nools/target-emitter.js
src/nools/task-emitter.js

This is an associated change from https://github.com/medic/cht-core/issues/5657. 
The ongoing Task and Target Improvements (Rules-Engine v2) which are happening in the 3.8 release require additional data about each task emitted by partner code. After upgrading to 3.8, the task and analytics tabs won't function until partner code is updated to send this new data.
The data can be included without affecting the behavior of the existing webapp. Therefore, we can make a change now to include the data in declarative partner configurations. The goal is that it won't affect anything in ongoing operations and projects will be able to seemlessly upgrade to 3.8 if they have deployed their configuration with medic-conf >3.1.0

Tasks and Targets v2 - Declarative configuration update to use new expected schema

---

src/fn/csv-to-docs.js
test/data/csv-to-docs/rel-dates/csv/report.relative_dates.csv
test/data/csv-to-docs/rel-dates/expected-json_docs/a73f33a9-b3ff-51b6-85d6-c18a65d85bb6.doc.json
test/data/csv-to-docs/rel-dates/expected-json_docs/f4ed6b3d-a89c-5d2a-9da4-e6c88d6f2e48.doc.json
test/data/csv-to-docs/rel-timestamps/csv/report.relative_timestamps.csv
test/data/csv-to-docs/rel-timestamps/expected-json_docs/0ca88f29-6ab4-596b-a04b-9dc40536cbdc.doc.json
test/data/csv-to-docs/rel-timestamps/expected-json_docs/4c9f8dfa-9463-5c05-afea-e19f087168ee.doc.json
test/data/csv-to-docs/rel-timestamps/expected-json_docs/def312ea-2bdd-59af-afc1-6800e87e526f.doc.json
test/fn/csv-to-docs.spec.js

As requested by @binokaryg we introduce two new types: `rel-date` to input relative dates and `rel-timestamp` to produce relative timestamp. The offset is in number of days from the time when `medic-conf` is executed.
https://github.com/medic/medic-conf/issues/230

Adds two new types to produce relative timestamps and relative dates

---

src/lib/upload-forms.js
src/lib/warn-upload-overwrite.js
test/lib/warn-upload-overwrite.spec.js

I was able to reproduce this bug. It occurs when the remote form does not exist so we fail to fetch the corresponding xml attachment.
https://github.com/medic/medic-conf/issues/278

Handles 404 from API (can't fetch xml attachment)

---

src/fn/move-contacts.js
src/lib/lineage-constraints.js
test/fn/move-contacts.spec.js

Add support for executing the `move-contacts` action when the parent is configured using the `contact_type` attribute (flexible hierarchy).
#286

Move-contact action should support use of contact_type

---

src/lib/main.js

This PR removes shebang on  this [line](https://github.com/medic/medic-conf/blob/master/src/lib/main.js#L1) that causes [Travis tests](https://travis-ci.org/medic/medic-conf/jobs/652976540?utm_medium=notification&utm_source=github_status) to fail on NodeJS version 12. 
cc @SCdF

Remove shebang - causes Travis tests to fail on Node.JS version 12

---

src/fn/upload-custom-translations.js
src/fn/upload-resources.js
src/lib/upload-forms.js
src/lib/warn-upload-overwrite.js
test/data/lib/upload-forms/merge-properties/forms/example.properties.json
test/data/lib/upload-forms/merge-properties/forms/example.xml
test/lib/upload-forms.spec.js
test/lib/warn-upload-overwrite.spec.js

Otherwise we skip over the form assuming that nothing has changed.
Additionally check local content against remote content before
checking stored hash to better detect when local is out of sync
with remote.
Also changes the hashes directory structure to support Windows. This
is not backwards compatible so users will be prompted to overwrite
the next time they upload config.
Additionally this change also makes it possible to configure the `xml2sms`
property on xforms.
#271
#300
#301
#303
#306

Check all form attributes when looking for change

---

src/lib/check-medic-conf-dependency-version.js
src/lib/main.js
test/lib/check-medic-conf-dependency-version.spec.js

REF #288 
So the rules for medic-conf version checking.:
- Newer medic-conf is ok as long as in the same Major version. No warning. So if medic-conf version is `3.1.2`, project version can be `3.0.0 - 3.1.2`
- Major version differing should always give an error. A suggestion to use `--skip-dependency-check` is given.

288 - medic-conf version check

---

.gitignore

Add .gitignore rules to omit IntelliJ* (IDEA, WebStorm...), Eclipse and Vi* configurations and temp files.

Add .gitignore rules

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md
.github/ISSUE_TEMPLATE/technical_issue.md
.github/PULL_REQUEST_TEMPLATE.md

Most of the issue templates are just copied from cht-core with minor modifications.

Add GitHub issue templates

---

release-notes.md

Added 3.3.0 release notes
medic/cht-core#6418

Release notes for 3.3.0

---

src/lib/api.js

Adding a call to the Deprecated Transition GET endpoint and log a warning if any of the new settings is enabling a deprecated transition.  
https://github.com/medic/medic-conf/issues/269
- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

269 - Log warning for deprecated transitions

---

src/contact-summary/contact-summary-emitter.js
test/contact-summary/contact-summary-emitter.spec.js

This PR makes a change to how `appliesToType` is processed such that if it is absent tthere is no effect and cards and fields should be displayed by default.
medic/medic-conf#164

164 applies to type optional

---

README.md

fixes travis link (cht-conf->medic-conf)
This also removes trailing whitespace (because my editor is set to do that automatically).

fixes travis link (cht-conf->medic-conf)

---

src/lib/upload-forms.js
test/data/lib/upload-forms/merge-properties/forms/example.properties.json
test/lib/upload-forms.spec.js

The hidden_fields propery is supported and should not WARN.
medic/medic-conf#377

Remove spurious warning

---

src/contact-summary/contact-summary-emitter.js
src/nools/target-emitter.js
test/contact-summary/contact-summary-emitter.spec.js
test/nools/target-emitter.spec.js

Only use `contact_type` field when `type` field value is `contact`. 
Fixes contact-summary fields and cards not being displayed correctly for contacts that use hardcoded types and have a `contact_property` field. 
Fixes these contacts not being counted towards target goals. 
medic/medic-conf#382
The software is provided under AGPL-3.0. Contributions to this …

Consistent contact type in contact summary and targets.

---

README.md
package-lock.json
package.json
src/bin/shell-completion.js
src/cli/usage.js
src/fn/check-git.js
src/fn/compress-pngs.js
src/lib/convert-forms.js
src/lib/environment.js
src/lib/exec-promise.js
src/lib/git-exec.js
src/lib/main.js
src/lib/user-prompt.js
test/lib/environment.spec.js
test/lib/exec-promise.spec.js
test/lib/git-exec.spec.js

Ticket: [medic-conf#64](https://github.com/medic/medic-conf/issues/64)
- The new action is called `check-git`, I tried to follow the convention name used in other action names, but I'm not 100% convinced of the name used, so I open to rename it.
- The implementation check local changes not commited and upstream changes, asking the user in both cases whether to continue or not.
- Add some refactors in the `exec-promise` module to be able to get the stout stream content that a command outputs, and also add the ability to silent or not the output regarless of the global log configuration. The PR adds also some unit tests to cover the `exec-promise` module.
- Pin "pluralize" dependency used in new module `git-exec` that was a dependency of dependency already.
Here is an example of the changes …

64 - New git-check action

---

src/lib/validate-declarative-schema.js
src/nools/task-emitter.js
test/lib/validate-declarative-schema.spec.js

Fix validations and task emitter that case actions with type "contact" don't follow the schema as expected, failing when when it tries to push the configurations.
medic/medic-conf#358
**In progress**:

Fix typo contact actions and schema validations (#358)

---

src/lib/api.js
src/lib/archiving-api.js
src/lib/archiving-db.js
src/lib/environment.js
src/lib/get-api-url.js
src/lib/validate-forms.js
src/lib/warn-upload-overwrite.js
test/fn/compile-app-settings.spec.js
test/fn/convert-forms.utils.js
test/fn/create-users.spec.js
test/fn/edit-contacts.spec.js
test/fn/initialise-project-layout.spec.js
test/fn/move-contacts.spec.js
test/fn/upload-branding.spec.js
test/fn/upload-custom-translations.spec.js
test/fn/upload-docs.spec.js
test/fn/upload-partners.spec.js
test/fn/upload-privacy-policies.spec.js
test/fn/upload-resources.spec.js
test/fn/upload-sms-from-csv.spec.js
test/lib/api.spec.js
test/lib/environment.spec.js
test/lib/main.spec.js
test/lib/upload-forms.spec.js
test/lib/validate-forms.spec.js
test/lib/warn-upload-overwrite.spec.js

If the user is running medic-conf in `--archive` mode and the local API is not running, avoid failing when the XForm validations are requested, and instead warn with the following message:
WARN The CHT Core instance is not running, no form will be checked before push
Also when trying to access other API endpoints and the API is down, there were messages logged like this: `ERROR Error trying to get couchdb config: RequestError: Error: Invalid URI "null//null@null/api/couch-config-attachments"` , now the message is:
ERROR Error trying to get couchdb config: RequestError: Error: connect ECONNREFUSED 127.0.0.1:5988
medic/medic-conf#396
- …

396 - XForm validations don't fail if archive mode

---

src/contact-summary/.eslintrc

A new variable called `uhcStats` is introduced the contact-summary script scope and this PR adds support in the eslint.
The [PR in cht-core](https://github.com/medic/cht-core/pull/7053) needs to be merged before this one.
https://github.com/medic/cht-core/issues/6919
The software is provided under AGPL-3.0. Contributions to this project are accepted under the …

Update eslint to recognise a new global in contact summary

---

src/lib/validate-declarative-schema.js
src/nools/definition-preparation.js
src/nools/task-defaults.js
src/nools/task-emitter.js
test/lib/validate-declarative-schema.spec.js
test/nools/mocks.js
test/nools/task-emitter.spec.js
test/run-nools-lib.js

Adds a default resolvedIf function for tasks.
Issue medic/medic-conf#107
Documentation PR: medic/cht-docs#466
- Uses [Utils.isFormSubmittedInWindow](https://github.com/medic/medic-nootils/blob/4339b25201bfbf51eef9179c8b7e0e92734a0d48/src/nootils.js#L57) to check if the resolving form has been submitted within a time period:
- For contact-based tasks, the period is the same as the task window period
- For report based tasks, the period is determined as follows:
- start: start of the task window or 1 millisecond after reported date of the source report, whichever comes later
- end: end of the task window
- The resolving form is the task's first action form with 'report' type
Options:
A. Skip `resolvedIf` section in the task definition, `defaultResolvedIf` will be used automatically
B. Using …

Add default "resolvedIf" function for tasks

---

README.md
src/contact-summary/.eslintrc
src/nools/.eslintrc

This PR adds the `cht` global to the eslint files.
https://github.com/medic/cht-core/issues/6914
CHT-Core: https://github.com/medic/cht-core/pull/7126
CHT-Docs: https://github.com/medic/cht-docs/pull/518 

6914 - Add global support for the cht script api

---

src/lib/main.js
test/lib/main.spec.js

Add a check to make sure the instance is reachable for actions that require an instance
medic/cht-conf#380

add check to ensure server is reachable

---

package-lock.json
package.json
release-notes.md

add 3.8.0 release notes and bump up version

---

src/lib/api.js
src/lib/archiving-api.js
src/lib/main.js
test/lib/api.spec.js
test/lib/main.spec.js

Move "ping" check to the `api` module, and implement the same in the `archiving-api` module for `--archive` mode.
medic/cht-conf#434
In the archive module is not expected the API to be running.
The call to `api().ping()` was moved after the `environment.initialize(..)` call, because the api module requires that initialization to happens first.
The software is …

Fix archive mode not working with no instance

---

CHANGELOG.md
package-lock.json
package.json

provide mecid-ci with write permissions to npm
medic/cht-conf#[413

feat(#413): provide mecic-ci with write permissions to npm

---

package-lock.json
package.json

Review please @mrsarm ... just bumping the translation lib version.
#455 

fix(#455): allow empty translation constants

---

src/lib/sync-fs.js
src/lib/upload-forms.js
test/lib/upload-forms.spec.js

https://github.com/medic/cht-conf/issues/395

XML Version as File Modified time

---

src/lib/validate-app-settings.js
test/lib/validate-app-settings.spec.js

The initial request was to make the regex more inclusive to support all unicode characters, but in investigating the parsing code I realised we allow multiple different formats for SMS messages, some of which allow for a wide range of possible characters in form and field names. This change removes all schema limitations from the form and field names other than forcing them to be strings of length at least 1.
medic/cht-conf#471
- Backwards compatible: Works with existing data and …

Allow more characters in form and field names

---

.github/workflows/release.yml
.releaserc.json
CHANGELOG.md
README.md
release-notes.md
src/fn/compress-svgs.js
src/lib/git-exec.js
test/lib/git-exec.spec.js

This pull request is part of the changes for ticket https://github.com/medic/cht-core/issues/6574. With this, we are addressing the changes needed for the https://github.com/medic/cht-conf repo.
I talked with @garethbowen before proceeding with the modifications. In order to try to reduce the downtime as much as possible without needing to do a lot of extra work, these are the steps to do to update the default branch name.
Note: any other pending pull request that was targeting master gets updated immediately by GH and references main instead after step #2 has been completed.
- Documented: Configuration and user documentation on …

Updating references from master branch to main

---

.github/workflows/release.yml
.releaserc.json
CHANGELOG.md
README.md
release-notes.md
src/fn/compress-svgs.js
src/lib/git-exec.js
test/lib/git-exec.spec.js

Changed a few files, both functional and notes, to stop referencing master branch and use main branch instead.
A few references to master were not updated as the main branch does not exist in those repos yet (for instance, cht-core)
[description]
medic/cht-conf#[number]
The software is provided under AGPL-3.0. Contributions to this project are accepted under …

Updated references from master branch to main

---

src/cli/usage.js
src/fn/validate-app-forms.js
src/fn/validate-collect-forms.js
src/fn/validate-contact-forms.js
src/fn/watch-project.js
src/lib/environment.js
src/lib/main.js
src/lib/upload-forms.js
src/lib/validate-forms.js
src/lib/validation/form/README.md
src/lib/validation/form/can-generate-xform.js
src/lib/validation/form/has-instance-id.js
test/fn/watch-project.spec.js
test/lib/main.spec.js
test/lib/validate-forms.spec.js
test/lib/validation/form/can-generate-xform.spec.js
test/lib/validation/form/has-instance-id.spec.js

Adds new actions for validating app/collect/contact forms without calling the `validate-*-forms` actions.  Refactors the validate code to be modular so that it can be easily expanded in the future (following the same pattern as the cht-conf `actions`).  This is basically an implementation of [option A](https://github.com/medic/cht-conf/issues/481).
Also adds support for the `--skip-validate` flag which will cause all form validation to be totally skipped.
Closes #481

feat(#484): add actions for validating forms

---

README.md

This step is no longer performed since we have updated this repo to be continuously deployed.
Context: [internal Slack discussion](https://medic.slack.com/archives/C03H77DKY0M/p1655933143379659).

chore: Remove forum announcement from release steps

---

package-lock.json
package.json
src/lib/forms-utils.js
src/lib/validate-forms.js
src/lib/validation/form/check-xpaths-exist.js
src/lib/validation/form/has-instance-id.js
src/lib/warn-upload-overwrite.js
test/lib/forms-utils.spec.js
test/lib/validate-forms.spec.js
test/lib/validation/form/check-xpaths-exist.spec.js
test/lib/validation/form/has-instance-id.spec.js

Adds support for validating simple XPath expressions in form XML files.  Simple XPaths, (ones that only describe a full path (either absolute or relative) to a node) in forms should always refer to a node that actually exists in the form (otherwise they would never actually result in a value).  XPaths that fail this check are almost certainly a bug.  
More complex XPath's (that might have conditional logic that depends on the actual data in the form) are not evaluated.
Note that I have only been able to find one "false positive" case (where an error is flagged when it should not be).  This case requires the XPath expression to include:
- Multiple string literals that are quoted using different quotes (single quotes vs double quotes)
- (note that XPath does not support escape characters so …

Add validation for simple XPaths in form config

---

test/fn/watch-project.spec.js

Currently, after running `npm test` on a freshly checked out version of `cht-conf`, you will notice that there are several uncommitted changes in the repo directory.  Basically, the https://github.com/medic/cht-conf/blob/main/test/fn/watch-project.spec.js tests end up adding/modifying several files that are not cleaned up when the test finishes:
```.sh
❯ git status
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   test/data/skeleton/app_settings.json
modified:   test/data/skeleton/translations/messages-en.properties
Untracked files:
(use "git add <file>..." to include in what will be committed) …
```

chore(#497): Add additional cleanup for the watch-project tests

---

src/lib/validation/form/no-required-notes.js
test/lib/validate-forms.spec.js
test/lib/validation/form/no-required-notes.spec.js

Adds a new validation that looks for note fields in a form that are required. These fields will cause issues with new versions of Enekto since they do not technically have a value and will block the progression of the form if they are required.  
Note that the [`countdown-timer`](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#cht-xform-widgets) widget also leverages a `note` field. Required countdown timers will also be flagged by this validation as they present the same behavior issues as regular notes.
Closes https://github.com/medic/cht-conf/issues/494
- Documented: Configuration and user documentation on …

feat(#494): validate notes are not required in forms

---

.github/workflows/build.yml
.github/workflows/release.yml

Updates the GitHub workflows so that they run on the latest `ubuntu-22.04` image.  Note that the `build` workflow could not actually be updated to 22.04 since it depends on Python 2. So, I have pinned it at 20.22 and listed this as something that should be changed when we [uplift our base Python version](https://github.com/medic/cht-core/issues/6537).
https://github.com/medic/cht-core/issues/7741
- Backwards compatible: Works with existing data and configuration. Any breaking …

Uplift GitHub workflows to run on ubuntu-22.04

---

src/nools/target-emitter.js
test/nools/target-emitter.spec.js

This PR changes the target emitter to default to now when the config target date is null or is a function that returns null.
medic/cht-conf#516

Target date default to Now #7711

---

.gitignore
src/lib/convert-forms.js
src/lib/forms-utils.js
test/lib/convert-forms.spec.js

Escapes whitespaces in path before converting forms.
Closes #504 

fix(#504): escape whitespaces in path when converting forms

---

README.md

Documentation for how to use the cht-app-ide image as a VS Code Dev Container was moved to the docs site. I am removing it from the README so it is not duplicated here.
medic/cht-conf#545

feat(#545): publish cht-app-ide docker image

---

src/fn/upload-extension-libs.js
test/fn/upload-extension-libs.spec.js

Fixes
medic/cht-conf#555
Ensure that upload-extension-libs doesn't throw an error when `extension-libs` folder doesn't exist. The action warns and continues. 

Fix #555 for non-existing directory

---

.github/workflows/publish_docker_image.yml

The saga continues....  I used the Docker admin account from 1Password to create https://hub.docker.com/r/medicmobile/cht-app-ide as a public repo. Unfortunately, it seems like the `dockermedic` account does not have permissions to push to `medicmobile` (it also did not have permissions to create a new repo in that org).  I tried locally using `medicmobile` to push an image and got the same `denied: requested access to the resource is denied` error that [we are seeing in the CI](https://github.com/medic/cht-conf/actions/runs/4791367443/jobs/8560319565).
Since the [openmin-mediator workflow](https://github.com/medic/cht-interoperability/blob/main/.github/workflows/docker-build.yml) can successfully push images with the creds configured in `DOCKERHUB_USERNAME`/`DOCKERHUB_TOKEN` I am going …

fix(#554): update docker creds used to push cht-app-ide image

---

.github/workflows/build.yml

Closes https://github.com/medic/cht-conf/issues/562
Python 2.x is [no longer supported](https://github.com/actions/setup-python/issues/672) by the official `setup-python` GitHub Action.  However, I do not believe there is anything stopping us from just building cht-conf with Python3 (installed by default on the `ubuntu` image).  
This PR just removes the `setup-python` config for the GetHub action and allows the build to run with the default Python3 (the same as the [cht-core GitHub action](https://github.com/medic/cht-core/blob/ba3b0c437b3b9105c0a523edf5d497a2a1a885ad/.github/workflows/build.yml#L149) (Additionally, I have removed the step for installing `wheel` since that is already included for python3 on the `ubuntu` image.)
- Readable: Concise, well named, follows the [style …

chore(#562): use default Python3 for GitHub action

---

src/lib/validate-app-settings.js
test/lib/validate-app-settings.spec.js

Accept dates on start_from
medic/cht-conf#578
Related to medic/cht-core#8633

feat(#578): accept array for start_from

---

src/lib/environment.js
src/lib/get-api-url.js
src/lib/main.js
test/lib/get-api-url.spec.js

--accept-self-signed-certs is just too long
medic/cht-conf#586

chore(#586): allow self signed certs by default for localhost-like hosts

---

package-lock.json
package.json
src/lib/api.js
test/fn/create-users.spec.js
test/fn/upload-custom-translations.spec.js
test/fn/watch-project.spec.js
test/lib/api.spec.js
test/lib/warn-upload-overwrite.spec.js

Leverage [async-retry](https://github.com/vercel/async-retry) to retry failed HTTP requests
medic/cht-conf#575

feat(#575): retry failed HTTP requests

---

src/lib/compilation/package-lib.js

use `require.resolve` to get the proper path to the webpack loader
medic/cht-conf#593

fix(#593): properly resolve the path to webpack loaders

---

src/fn/upload-app-settings.js
src/lib/get-api-version.js
test/fn/upload-app-settings.spec.js

[description]
medic/cht-conf#596

fix(#596) fix issue with semver validation for latest versions

---

test/lib/get-api-version.spec.js

Fixes medic/cht-conf#596
Actual work was done on #597 , this one adds test and is for release purpose. 

fix(#596): fix issue with semver

---

.github/workflows/build.yml
.github/workflows/release.yml

[description]
medic/cht-conf#599

fix(#599): support node 20

---

src/lib/environment.js
test/lib/environment.spec.js
test/lib/upload-forms.spec.js

Fixes issue with #602, which was cause by recent change in apiUrl
medic/cht-conf#602

fix(#602):  fix errors with validate functions

---

src/fn/csv-to-docs.js
src/lib/sync-fs.js
test/fn/csv-to-docs.spec.js
test/lib/sync-fs.spec.js

Added warning if `jsonDir` contains files when running `csv-to-doc` command.
medic/cht-conf#26
1. When `jsonDir` does not exists
2. When `jsonDir` exists and user wants to continue after prompt is shown
3. When `jsonDir` exists and user does not want to continue after prompt is shown
The software is provided under AGPL-3.0. Contributions to this project are …

fix(#26): add warning if jsonDir contains file when running csv-to-doc command

---

.github/workflows/build.yml
.github/workflows/publish_docker_image.yml
.github/workflows/release.yml
README.md
package-lock.json
package.json

Dropping support for NodeJS < 18.
medic/cht-conf#600

perf(#600): drop support for Node versions < 18

---

Dockerfile
test/e2e/.mocharc.js

Now that we are supporting Node 20, we can bump the version of Node used in the Dockerfile. The only impact this had is that the newer Python package is now requiring we install pyxform [into a virtual environment](https://medic.slack.com/archives/C024KTGRW/p1722392539299829).  
One solution would be to just run the `pip install` with the `--break-system-packages` flag which should be fine in a simple Docker image like this since the whole point of the containerization is that we don't have competing dependency stacks.  
That being said, after doing [some reading](https://pythonspeed.com/articles/activate-virtualenv-dockerfile/) I have instead opted for actually using a virtual environment here. It was not too much trouble and it felt more future-proof (and less janky).  
We do not have …

chore: update Dockerfile to be based on the Node 20 image

---

README.md

Some occurrences of `cht-conf` in the README file were incorrect, and have been replaced with `cht`.
medic/cht-conf#632

fix(#632): replace `cht-conf` with `cht` in readme.md

---

.github/workflows/build.yml
test/e2e/edit-app-settings.spec.js

Update github-action `upload-artifact` to version 4. More details in the issue.
medic/cht-conf#635

fix(#635): update upload-artifact GH action to version 4

---

src/fn/initialise-project-layout.js

Closes #657
Removes the invalid comma from the `.eslintrc` file that gets created by the `initialize-project-layout` action.

fix(#657): remove invalid comma from .eslintrc

---

.editorconfig

added the editorconfig file based on the stytle guide here https://docs.communityhealthtoolkit.org/contribute/code/style-guide/
Closes #611 

chore(#611): add editorconfig file based on the style guide

---

src/lib/upload-forms.js
test/data/lib/upload-forms/duplicate_check-properties/forms/contact/example.properties.json
test/data/lib/upload-forms/duplicate_check-properties/forms/contact/example.xml
test/data/lib/upload-forms/duplicate_check-properties/forms/report/example.properties.json
test/data/lib/upload-forms/duplicate_check-properties/forms/report/example.xml
test/lib/upload-forms.spec.js

Add support for consuming and uploading the `duplicate_check` property when processing `contact` form `.properties` files.
Closes https://github.com/medic/cht-conf/issues/675

fix(#675): support duplicate_check prop

---

src/lib/validation/form/deprecated-appearance.js
test/lib/validation/form/deprecated-appearance.spec.js

We add deprecation warnings when using the `db-object` appearance instead of the new `select-contact` appearance.
We also update the `ERROR_HEADER` to be more
generic.
Related discussion: https://forum.communityhealthtoolkit.org/t/warn-when-using-deprecated-db-object-appearance/4890/
Fixes #502.
The software is provided under AGPL-3.0. Contributions to this …

feat(#502): warn when using deprecated `db-object` appearance

---

README.md
src/cli/shell-completion-setup.js
src/cli/shell-completion.zsh

added autocompletion feature similar to bash for zsh
closes #683 

feat(#683): add autocompletion feature for zsh 

---

.github/workflows/build.yml
.github/workflows/release.yml
package.json

Closes #712 
https://endoflife.date/nodejs
Add NodeJS 24 as a target.
BREAKING CHANGE: remove support for NodeJS 18

feat(#712)!: update targeted NodeJS versions
